### ISSUE TITLE
Multiple unused variables

### ISSUE THREAD

**Issue by Hazzoz** [synesissoftware/STLSoft-1.10#14]
`Building CXX object test/scratch/test.scratch.links/CMakeFiles/test_scratch_links.dir/test.scratch.links.cpp.o
In file included from /Users/harrywilson/Hazzoz/recls/test/scratch/test.scratch.links/test.scratch.links.cpp:17:
In file included from /Users/harrywilson/Hazzoz/recls/include/recls/recls.hpp:62:
In file included from /Users/harrywilson/Hazzoz/recls/include/recls/cpp/entry.hpp:71:
In file included from /usr/local/include/platformstl/filesystem/filesystem_traits.hpp:75:
In file included from /usr/local/include/unixstl/filesystem/filesystem_traits.hpp:79:
In file included from /usr/local/include/unixstl/filesystem/path_classify_functions.h:157:
/usr/local/include/unixstl/filesystem/path_functions/classify_functions_X_.h:293:29: error: variable 'prev' set but not used [-Werror,-Wunused-but-set-variable]
        char_t const*       prev        =   ss_nullptr_k;
                            ^
1 error generated.
make[2]: *** [test/scratch/test.scratch.links/CMakeFiles/test_scratch_links.dir/test.scratch.links.cpp.o] Error 1
make[1]: *** [test/scratch/test.scratch.links/CMakeFiles/test_scratch_links.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by mwsis** [comment]
Fixed as of **1.10.3**
