### ISSUE TITLE
why not support clang++

### ISSUE THREAD

**Issue by fndisme** [synesissoftware/STLSoft-1.10#4]
When I just put stlsoft into project and just change g++ to clang++, compile failed. It's great lib but need more for support new compile and c++17 and more.

**Comment by synesissoftware** [comment]
There've been a bunch of updates lately. If you get a chance, please let me know whether it's now satisfying your needs

**Comment by fndisme** [comment]
That's great, I will try it!

**Comment by mwsis** [comment]
Hi. I recognise that this has been a very long-time in response - I've been working in a context where it wasn't C++ and I was not permitted to do open source (even if I'd had the time, which was not so) - but I'm keen to catch up on all things STLSoft in the coming days. I've just released 1.10.1 proper, and am now looking into reported issues.

Can you recall the context in which this occurred? I'm having trouble replicating, and I think the changes released in 2021 may have it covered.

Using the (very) simple program file **test/scratch/versions/versions.iostreams/versions.cpp** (in the project, on **master**), I don't have any problem with any of the following commands.

- `$ g++ -I ../../../../include -std=c++11 ./versions.cpp`
- `$ g++ -I ../../../../include -std=c++14 ./versions.cpp`
- `$ g++ -I ../../../../include -std=c++17 ./versions.cpp`
- `$ g++ -I ../../../../include -std=c++20 ./versions.cpp`
- `$ clang++ -Wall -Werror -pedantic -I ../../../../include -std=c++11 ./versions.cpp`
- `$ clang++ -Wall -Werror -pedantic -I ../../../../include -std=c++14 ./versions.cpp`
- `$ clang++ -Wall -Werror -pedantic -I ../../../../include -std=c++17 ./versions.cpp`
- `$ clang++ -Wall -Werror -pedantic -I ../../../../include -std=c++20 ./versions.cpp`

I'm happy to follow up in a timely manner if you can elucidate.

Thanks

Matt

Absolutely no problems if you're no longer interested, and appreciate the effort you made back then.

**Comment by synesissoftware** [comment]
Closed, as have verified myself
